export const AllProducts = [
    {
      id: 1,
      name: "Shaving gel Mercado Barbeiro Signature",
      img: ["/img/01/01.jpg", "/img/01/02.jpg", "/img/01/03.jpg", "/img/01/04.jpg"],
      old:48.5,
      price: 38.5,
      category: "BARBA",
      mark: "SHAVING",
      condition: "",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 2,
      name: "Bico Borrifador Aplicador de Toppik",
      img: ["/img/02/01.jpg"],
      old:88.5,
      price: 60.5,
      category: "BARBA",
      mark: "Toppik",
      condition: "4x de R$ 20,16 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 3,
      name: "Toppik Black 27.5G",
      img: ["/img/03/01.jpg"],
      old: 142,
      price: 121,
      category: "BARBA",
      mark: "Toppik",
      condition: "6x de R$ 20,16 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 4,
      name: "Beard Balm - Balm para a Barba",
      img: ["/img/04/01.png"],
      old: 65.98,
      price: 54.99,
      category: "BARBA",
      mark: "Beard",
      condition: "2x de R$ 27,49 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 5,
      name: "Bead Oil - Oléo para Barba Kraft Men Care 30ml",
      img: ["/img/05/01.jpg"],
      old: 75.98,
      price: 65.99,
      category: "BARBA",
      mark: "Kraft",
      condition: "3x de R$ 21,99 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 6,
      name: "Tônico capilar Big Barber 120ml Blend de crescimento",
      img: ["/img/06/01.jpg"],
      old: 49.99,
      price: 35,
      category: "BARBA",
      mark: "Big Barber",
      condition: "",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 7,
      name: "Gel de Barbear Shave Design Ferramentas de Barbeiro 1kg",
      img: ["/img/07/01.png"],
      old: 79.99,
      price: 68.5,
      category: "BARBA",
      mark: "Shave",
      condition: "6x de R$ 11,42 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 8,
      name: "Kit Para Barba – Gel de Barbear 1kg + Pós-Barba 500g + Óleo Para Barba 30ml",
      img: ["/img/08/01.png"],
      old: 148.55,
      price: 136,
      category: "BARBA",
      mark: "Shave",
      condition: "6x de R$ 22,75 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 9,
      name: "Fixador De Cabelo Grooming Peaky Blinders",
      img: ["/img/09/01.jpg"],
      price: 89,
      category: "CABELO / BARBA",
      mark: "Peaky Blinders",
      condition: "8x de R$ 11,12 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 10,
      name: "Creme De Barbear Militaer 500gr",
      img: ["/img/10/01.jpg"],
      old: 78,
      price: 69,
      category: "CABELO / BARBA",
      mark: "Militaer",
      condition: "6x de R$ 11,50 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 11,
      name: "Condicionador Masculino Keune Essential 250ml Formula Única",
      img: ["/img/11/01.jpg"],
      price: 129.9,
      category: "CABELO / BARBA",
      mark: "Keune",
      condition: "10x de R$ 12,99 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 12,
      name: "Fixador De Cabelo Hairspray Don Alcides Freak Show",
      img: ["/img/12/01.jpg"],
      old: 101,
      price: 89,
      category: "CABELO / BARBA",
      mark: "Don Alcides",
      condition: "6x de R$ 14,84 sem juros",
      shortDesc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada.",
      Desc: "Mussum Ipsum, cacilds vidis litro abertis. Detraxit consequat et quo num tendi nada. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Manduma pindureta quium dia nois paga. Interagi no mé, cursus quis, vehicula ac nisi.",
      inCart: false,
      count: 0,
      total: 0
    }
  ];